### ISSUE TITLE
redis挂了，如何处理？

### ISSUE THREAD

**Issue by shuaigaoa** [7le/shine-mq#10]
如果redis挂了，持久化会丢最多1秒的数据，那么这部分异常的消息怎么处理？

**Comment by 7le** [comment]
@shuaigaoa 你说的持久化丢最多1秒的情况是指AOF下的每秒Fsync模式吧。
一般情况下，redis都是使用集群的，这样可以确保容灾。
如果是单机的redis，而且还要保证很高的可靠性，那就只能牺牲性能，使用AOF每次操作进行Fsync的模式了。
当然，还是推荐使用redis集群。

**Comment by shuaigaoa** [comment]
果然还是得上集群，还有一个问题咨询下，消息的分布式事务如何保证服务B的顺序消费？

**Comment by 7le** [comment]
@shuaigaoa 不建议保证服务B的顺序消费。因为保证严格顺序消息的代价非常大，你要允许消息可以丢失（这个是致命的，或者放弃一些性能使用事务提交），另外还要从发送方到服务方到接受者都是单点单线程。 
一般来讲，在分布式事务消息的设计里，应该是在不丢消息的前提下，尽量减少重复消息，不保证消息的投递顺序。建议你可以使用其他方式来避免这个问题，具体业务问题具体分析。
如果一定要实现顺序消费，就要使用单分区（或单queue）并保证消费者顺序消费了。
