### ISSUE TITLE
ready消息发送成功，调用方失败，如何处理？

### ISSUE THREAD

**Issue by Rocky-Hu** [7le/shine-mq#13]
发送ready消息的时候，ready消息发送成功，但是此时因为特殊原因，调用方业务回滚了（比如说宕机），那么ready消息被下游服务消费了，但是实际上上游服务是没成功的，不就有问题了吗？

**Comment by 7le** [comment]
@Rocky-Hu 这个ready消息，是会在commit之后才会触发发送的（比如使用``@DistributedTrans``），所以是不会有这个问题的。

**Comment by Rocky-Hu** [comment]
@7le 也就是说明确收到业务操作的执行成功结果后，才会调用发送ready消息，是这样吧？

**Comment by 7le** [comment]
@Rocky-Hu 是的。不然有异常是直接回滚的，进不到``DistributedTransAspect``这个切面
