### ISSUE TITLE
关于可靠消息 💡

### ISSUE THREAD

**Issue by 7le** [7le/shine-mq#8]
### 可靠消息的发送

消息的可靠发送可以认为是尽最大努力发送消息通知，有两种实现方法：

-  发送消息之前，把消息持久到数据库，状态标记为待发送，然后发送消息，如果发送成功，将消息改为发送成功。若有失败，定时任务将会定时从数据库捞取一定时间内未发送的消息，将消息发送。
- 实现方式与第一种类似，不同的是持久消息的数据库是独立的，并不耦合在业务系统中。发送消息之前，先发送一个预消息给某一个第三方的消息管理器，消息管理器将其持久到数据库，并标记状态为待发送，发送成功后，标记消息为发送成功。定时任务定时从数据库捞取一定时间内未发送的消息，回查业务系统是否要继续发送，根据查询结果来确定消息的状态。

在`shine-mq`已经做了两种实现方法共性的消息持久化工作，默认实现的持久消息数据库是`redis`，也可以自己实现`Coordinator`接口（自行实现的需要注入到spring容器）。而捞起的超时异常消息，要怎么处理就需要根据业务自行选择是否要回查。

另外这个定时任务是需要自己实现的，具体如何实现可以自由发挥了（例如可以在服务A里实现定时任务，或者有统一的`daemon`来做处理）。

* [分布式事务：消息可靠发送](https://7le.top/2019/02/21/%E5%88%86%E5%B8%83%E5%BC%8F%E4%BA%8B%E5%8A%A1%EF%BC%9A%E6%B6%88%E6%81%AF%E5%8F%AF%E9%9D%A0%E5%8F%91%E9%80%81/)

**Comment by superzw** [comment]
> 实现方式与第一种类似，不同的是持久消息的数据库是独立的，并不耦合在业务系统中。发送消息之前，先发送一个预消息给某一个第三方的消息管理器，消息管理器将其持久到数据库，并标记状态为待发送，发送成功后，标记消息为发送成功。定时任务定时从数据库捞取一定时间内未发送的消息，回查业务系统是否要继续发送，根据查询结果来确定消息的状态。

“回查业务系统是否要继续发送”回查如何实现？需要额外的表来记录吧？

**Comment by 7le** [comment]
@superevanzhu ``shine-mq``默认已经用redis实现了，也提供了``Coordinator``接口可以自行实现。

**Comment by superzw** [comment]
redis和db有数据一致性问题的啊，并不能保证100%可靠吧

**Comment by superevanzhu** [comment]
不通过本地消息表，理论上应该是做不到的

**Comment by 7le** [comment]
@superevanzhu 你说的一致性问题具体是指什么情况呢？用redis和本地消息表是没有不同的，都可以实现持久化，以及集群来保证高可用。

**Comment by superzw** [comment]
理解了 :)

**Comment by 7le** [comment]
好滴 :octocat:
