### ISSUE TITLE
关于死信队列 💡

### ISSUE THREAD

**Issue by 7le** [7le/shine-mq#9]
### 关于死信队列

在`shine-mq`使用分布式事务的时候会默认创建死信队列，死信队列的配置如下：
```
public static final String DEAD_LETTER_QUEUE = "dead_letter_queue";

public static final String DEAD_LETTER_EXCHANGE = "dead_letter_exchange";

public static final String DEAD_LETTER_ROUTEKEY = "dead_letter_routekey";
```

当服务B接收mq的消息失败次数大于`receiveMaxRetries`（默认为3，可以配置），就会将失败的消息投递到死信队列。死信队列的消息同样是可以进行消费，而如何来处理就是各自按着业务来实现了。

```
    @Autowired
    RabbitmqFactory factory;

    @PostConstruct
    public void test() {
        //配置死信队列 失败时候处理
        factory.add(MqConstant.DEAD_LETTER_QUEUE, MqConstant.DEAD_LETTER_EXCHANGE,
                MqConstant.DEAD_LETTER_ROUTEKEY, new ProcessorException(), SendTypeEnum.DLX);
    }

    /**
     * 处理异常消息
     */
    static class ProcessorException extends BaseProcessor {

        @Override
        public Object process(Object msg, Message message, Channel channel) {
            System.out.println("自行实现 通知人工处理 或者回调原服务A的回滚接口：" + msg);
            return null;
        }
    }
```

因为就实现了一条死信队列，多个分布式事务失败的消息都会被同一个死信队列的`processor`消费，这里可以根据`Message`获取对应原始的队列信息来区分处理。

**Comment by qracle** [comment]
![1551925074 1](https://user-images.githubusercontent.com/32318904/53928295-92130b00-40c4-11e9-8d93-4cc91dc4878d.jpg)
请问这两个方法放的位置没有问题吗？

**Comment by 7le** [comment]
@qracle 第一个方法是创建用来传输分布式消息的队列，第二个是创建死信队列嗯。

**Comment by qracle** [comment]
![image](https://user-images.githubusercontent.com/32318904/53929051-6d6c6280-40c7-11e9-99bc-f6cba4f94d8c.png)
@7le 在addDLX方法中的 isDlx 参数为true，然后走了上图的逻辑，添加了和死信队列相同的参数

**Comment by qracle** [comment]
@7le 我有两个问题想请教一下。
问题1：第一个方法addDLX改为add是不是同样的效果？
问题2：flag参数的作用是什么呢？为什么第一个方法不能放入if条件中呢？

**Comment by 7le** [comment]
@qracle 根据你的问题
回答1： 用add方法是不行的，这涉及到rabbitmq死信队列的实现（下面我简单描述下）
回答2： flag作用就是只创建一次死信队列（DLX最终路由的队列），虽然重复创建也创建不了，但是还是想省去多余的消耗。第一个方法是用来创建传递分布式消息的队列的，这个根据``@DistributedTrans``可以自定义多个的，如果只创建一个是不合理的。

> Rabbitmq的DLX:

DLX（Dead-Letter-Exchange）是一个正常的交换机，和一般的交换机没有区别，它能在任何的队列上被指定，实际上就是设置某个队列的属性，当这个队列中有死信时，RabbitMQ就会自动的将这个消息重新发布到设置的Exchange上去

上面的截图里，你也看到了，rabbitmq使用这个机制是需要2个参数的，用``x-dead-letter-exchange`` 来标识交换机  ``x-dead-letter-routing-key`` 来标识绑定键（RoutingKey）。然后这个绑定键是分配给标识的交换机的。当有队列通过此绑定键绑定到交换机，那么死信会被该交换机转发到该队列上。 

所以``rabbitmqFactory.add(MqConstant.DEAD_LETTER_QUEUE, MqConstant.DEAD_LETTER_EXCHANGE,MqConstant.DEAD_LETTER_ROUTEKEY, null, null);``这条队列就是死信队列最后将死信转发到的目的队列，可以监听这条队列来消费死信（一些失败或被拒绝的消息）。

而``addDLX``方法是创建队列的同事，将队列指定到DLX这个交换机，这样就可以将该队列中的死信路由到DLX了。

**Comment by qracle** [comment]
@7le 明白了，解释的很详细
边阅读你的文章边看你的代码，感觉收获挺多的
当然如果有些方法或者调用方法处能标记注释的话，理解起来可能就不会有那么多疑问了
期待你的更新！

**Comment by 7le** [comment]
@qracle 好滴，我以后多增加注释 :smile:

**Comment by qracle** [comment]
![image](https://user-images.githubusercontent.com/32318904/53943582-598d2480-40f8-11e9-9bbc-3ac8586a6f5e.png)
![image](https://user-images.githubusercontent.com/32318904/53943634-76c1f300-40f8-11e9-8133-bf7817d017f8.png)
![image](https://user-images.githubusercontent.com/32318904/53943848-fb147600-40f8-11e9-869c-b9f0fe2bab6e.png)

@7le 有个疑问，checkBackId为标注@DistributedTrans方法的返回值，并且checkBackId会被用作为存储在redis中的key
问题1：如果返回值是一个大的json对象，作为redis的key是否会造成redis的key的长度太长，导致性能下降？

问题2： 如果一个请求进入服务A，服务A插入数据，服务A需要调用服务B的接口，并且将服务A方法中计算好的值作为参数传入服务B，服务B再插入数据，那么这个时候就会存在分布式事务。那么这种情况下是如何使用这个jar包来解决问题的，在demo中没有找到相关的代码。举个例子，在spring cloud中微服务相互之间用通过feign接口调用，这个时候还能在调用方的方法上使用@DistributedTrans注解吗？

问题3：如问题2的场景，checkBackId作为一个标注@DistributedTrans方法的返回值，并且作为服务B需要的参数，在服务B端能通过实现Process接口的process方法拿到，然后插入数据库，这样理解对吗？

**Comment by 7le** [comment]
@qracle 
在回答你的问题前，我先说一下这个**checkBackId**的作用，在[分布式事务：基于可靠消息服务](https://7le.top/2018/12/04/%E5%88%86%E5%B8%83%E5%BC%8F%E4%BA%8B%E5%8A%A1%EF%BC%9A%E5%9F%BA%E4%BA%8E%E5%8F%AF%E9%9D%A0%E6%B6%88%E6%81%AF%E6%9C%8D%E5%8A%A1/#more)中，有一段:

另外还有一个比较关键的daemon（守护线程），是处理在Coordinator一些错误超时的记录（类似Rocketmq的超时询问机制）。所以服务A除了实现正常的业务流程外，还需提供一个事务询问的接口，供Coordinator调用，来保障服务A在执行任务出现宕机的情况。当有prepare超时就会触发访问这个回查接口，该接口会返回三种结果：                                                                                                              
* 提交 将该消息投递
* 回滚 直接将条消息丢弃
* 处理中 继续等待，重置时间。

这里的回查服务A的接口，来判断是哪个任务就是靠这个**checkBackId**。看图会更清晰点，

![checkbackid](https://user-images.githubusercontent.com/25902183/53950354-ec34c000-4106-11e9-9ebd-528977689c36.PNG)

现在回答你的问题：
回答1： 看了上面的描述，**checkBackId**是被设计用来做回查的回查Id，是不应该被设计成一个成json，理想的设计会类似一个分布式id（比如**snowflake**）。
PS. 感谢你的细心提问。我在看你的问题的时候，发现了上个版本加**checkBackId**遗漏的一点问题，我当时忽略了服务A向服务B可能需要发送对应的业务数据了，直接用**checkBackId**覆盖了原来的**data**，我这几天会再发个版本，把这个问题修复掉，会兼容**checkBackId**和**data**，在你的问题2，3中是需要**data**的。

回答2，3：是的，就是按你描述的，在服务B端通过实现Process接口的process方法拿到。
然后**feign**的问题，**feign**的本质也是一种远程调用（基于http），如果要实现分布式事务，会有点类似TCC。这里就不展开了，分析起来情况也会非常多。这个跟**shine-mq**在设计上就不太一样，是不能一起用的。我说的不能一起用是指不能加在``@FeignClient``注解的接口上，如果是调用该接口的方法上，用``@DistributedTrans``是没影响的，只不过它们会各处理各的切面。

**Comment by qracle** [comment]
@7le 非常感谢耐心解答，确实之前读文章遗漏掉了daemon的逻辑。
希望在shine-mq-demo项目中能有一个完整的示例供我们学习者参考吧！
期待你的更新！

**Comment by qracle** [comment]
![image](https://user-images.githubusercontent.com/32318904/54018868-b9e99800-41c4-11e9-943c-c33b287f3a8d.png)
关于以上这段话的理解和疑惑：
1.守护线程设计为一个定时任务，定时调用Coordinator的getPrepare()和getReady()方法，可以分别获取到超时的checkBackId和EventMessage对象，文中提到的事务询问的接口是否就是以上两个方法？
2.服务A返回状态给daemmon，这三种状态是在哪定义的，是需要在服务A端自定义吗？
3.如果prepare能对三种状态做处理，那必须要有原调用方法的上下文才能做处理吧。

这段话结合代码看了很多遍，总感觉服务A和daemon这个回路实现起来有不对劲，是不是我的理解上出了一些问题？ 感觉思路有点乱了。。。

**Comment by 7le** [comment]
@qracle 
对于**Prepare**的流程是这样的：
* 在服务A处理任务A前，首先向Coordinator发送一条prepare（携带回查id）记录，表示要开始这个分布式任务
* Coordinator持久化prepare记录后响应服务A
* 服务A收到确认应答后，服务A处理任务A，成功后发送一条ready记录，Coordinator将删除之前对应的prepare记录，并持久化ready记录和完整的消息

但是可能会出现一些极端情况（网络中断或者服务宕机等），**Coordinator**没有收到后续的**ready**消息，而服务A也没有投递消息到mq，这时候我们就不知道当时发生极端情况下的任务A状态（可能成功、失败或者其他，这个就是根据自己的业务来定义了，也不一定是我写的三种，甚至更多，或者更少），我们假设任务A是在数据库插入一条数据，然后对应的id为checkBackId。

这时候我们就需要用``getPrepare()``来捞取超时的**prepare**，在**prepare**消息中会有之前带着的checkBackId，这里要调用服务A提供的回查接口（这个需要服务A自己实现），对应的参数就是回查Id，那就可以知道任务A是否完成了，然后根据返回的状态再做其他的补偿操作。

ready跟prepare差不多的，更加简单点。只要有捞到超时的，只管投递到mq就行。**因为只要是ready消息持久化到Coordinator，那就说明服务A的任务已经完成。**

我后续补一个比较完整的demo到[shine-mq-demo](https://github.com/7le/shine-mq-demo)吧，现在的demo比较简单，没有带回查机制，就是简单的[服务A](https://github.com/7le/shine-mq-demo/tree/master/distributed-transaction)  和[服务B](https://github.com/7le/shine-mq-demo/tree/master/distributed-transaction-consumer)。

**Comment by qracle** [comment]
@7le 博主大大，请问什么时候能更新完整Demo呢，非常期待！

**Comment by 7le** [comment]
@qracle 不好意思哈，最近有点忙碌一直耽搁了，我争取在这两周会更新出来。 感谢你的关注~ :octocat:

**Comment by 7le** [comment]
@qracle 已经更新了，地址在这[shine-mq-demo](https://github.com/7le/shine-mq-demo)。对应的[服务A](https://github.com/7le/shine-mq-demo/tree/master/distributed-transaction)，[服务B](https://github.com/7le/shine-mq-demo/tree/master/distributed-transaction-consumer)。:smile:

**Comment by qracle** [comment]
@7le 很棒，最近才看到，非常感谢博主的耐心解答！

**Comment by qracle** [comment]
@7le 还有一个小问题，在配置类MqAutoConfiguration中@Import并未引入RedisUtil类，在Demo的生产者项目中可以自动注入RedisUtil吗？好像启动类也没扫描到这个目录。。。其实我想知道的是，像这种自定义的starter，如果项目A引入了该依赖，想要在项目A中自动注入该jar包中的Bean，那么是不是需要在自定义starter类中@Import中加入该类标识，或者是说在spring.factories中引入写入类路径，或者是在项目A启动类上配置starter包路径。

**Comment by 7le** [comment]
@qracle 嗯，你说几种方式都是可以的。
而对于RedisUtil，我是做了配置的过滤，只有**shine.mq.distributed.redis-persistence**该参数为true的时候才会加入到容器。毕竟不用redis的话，也用不到这个类。对应的代码如下：
```
@Bean
@ConditionalOnProperty(name = "shine.mq.distributed.redis-persistence",
        havingValue = "true", matchIfMissing = true)
public RedisUtil redisUtil() {
        return new RedisUtil();
}
```

**Comment by qracle** [comment]
@7le 明白了，非常感谢！

**Comment by qracle** [comment]
![1556631575231](https://user-images.githubusercontent.com/32318904/56965715-7b52d700-6b90-11e9-8e2f-47c0bbc483c0.jpg)
发现了一个小问题，在测试处理prepare消息时，发现getPrepare()拿到的永远是空，发现超市时间判断这边返回的是false，应该换成小于号吧。换成小于号就能正常拿到prepare消息了

**Comment by 7le** [comment]
@qracle 这个是对的。 你没理解清楚prepare消息的作用，建议你自己好好再看看。这个本来就不应该拿到的，只有出现异常才会拿到。

**Comment by qracle** [comment]
@7le 嗯嗯，你是对的。顺便问一下，框架提供的分布式事务注解是可以和Spring提供的@Transactional一起使用的吧！

**Comment by 7le** [comment]
@qracle 嗯，可以共用的。

**Comment by kindess** [comment]
![K`1@`1AX8V
A ~VR7RBDSU](https://user-images.githubusercontent.com/44660131/94126097-c5c1ab80-fe89-11ea-8249-e50a4b383761.png)
这里创建队列和交换机的时候，即使队列和交换机缓存命中了，routingKey不同，是不是也需要重新执行绑定吧

**Comment by 7le** [comment]
![image](https://user-images.githubusercontent.com/25902183/94221386-92306100-ff1d-11ea-9a94-fa08b0a07123.png)
网上拿了张图，方便解释。
1.生产者先发送消息到Exchange。
2.Exchange通过绑定的routekey发送到Queue。
3.消费者只需要监听队列，Queue将消息push到消费者。

所以routekey是用来绑定queue，可以理解为该Exchange下该queue的标示。
那如果该Exchange和queue被缓存命中(已经创建过)，那就不需要再绑定了。因为不会出现同exchange，同queue，不同routingKey情况。
不知道是否可以解你的疑惑🤔

**Comment by kindess** [comment]
假设已经存在缓存2个topic交换机，2个队列，但是交叉绑定的时候不会出问题吗？

**Comment by 7le** [comment]
@kindess 确实加了**needBinding**会有这种极端情况的问题，我后续修复下～
